[package]
name = "llama"
version = "0.1.0"
edition = "2021"
description = "Simple LLaMA decoder written in rust"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
bytemuck = "1.16.3"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"
